server:
  port: ${PORT:8081}
  servlet:
    context-path: /profiles

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

config:
  http:
    file: https://file-service-cdal.onrender.com
    mail: ${MAIL_SERVICE_URL:https://mail-service-80a4.onrender.com}

spring:
  application:
    name: profile
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 0
          use_streams_for_binary: false
        cache:
          use_second_level_cache: false
          use_query_cache: false
        connection:
          provider_disables_autocommit: false
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0&preparedStatementCacheQueries=0&preferQueryMode=simple}
    username: ${DATABASE_USERNAME:postgres.noyltxzqpksuzxmjonkm}
    password: ${DATABASE_PASSWORD:Cong2642005@@}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      max-lifetime: 300000
      connection-timeout: 20000
      connection-test-query: null
      validation-timeout: 3000
      idle-timeout: 60000
      auto-commit: false
      connection-init-sql: SELECT 1
