server:
  port: ${PORT:8081}
  servlet:
    context-path: /profiles

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

config:
  http:
    file: https://file-service-cdal.onrender.com
    mail: ${MAIL_SERVICE_URL:https://mail-service-80a4.onrender.com}

spring:
  application:
    name: profile
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://dpg-d41p7um3cjmc738t8o6g-a.singapore-postgres.render.com:5432/database_pym9?sslmode=require}
    username: ${DATABASE_USERNAME:lethanhcong}
    password: ${DATABASE_PASSWORD:zMna2eG7LBmjIZvGvMqOibJMSou9ys23}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
