server:
  port: ${PORT:8081}
  servlet:
    context-path: /profiles

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

config:
  http:
    file: https://file-service-cdal.onrender.com
    mail: ${MAIL_SERVICE_URL:https://mail-service-80a4.onrender.com}

spring:
  application:
    name: profile
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require}
    username: ${DATABASE_USERNAME:postgres.noyltxzqpksuzxmjonkm}
    password: ${DATABASE_PASSWORD:Cong2642005@@}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
